import {test,expect} from '@playwright/test';
async function load(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('/?debug=1');await expect(page.locator('#start')).toBeEnabled();return errors;}
async function start(page){await page.locator('#start').click();await page.locator('#racebtn').click();await expect(page.locator('#race')).toBeVisible();await page.evaluate(()=>MR.debug.skipCountdown());}
async function controlPoints(page,selectors){return Promise.all(selectors.map(async selector=>{const b=await page.locator(selector).boundingBox();return {x:b.x+b.width/2,y:b.y+b.height/2,id:selectors.indexOf(selector)+1};}));}
test('garage, six WebGL meshes, RU/UZ/EN, race start and independent cameras',async({page},info)=>{
 const errors=await load(page);await page.locator('#set').click();await page.locator('#lang').selectOption('en');await expect(page.locator('#st')).toHaveText('SETTINGS');await page.locator('#lang').selectOption('uz');await expect(page.locator('#st')).toHaveText('SOZLAMALAR');await page.locator('#lang').selectOption('ru');await page.locator('#laps').selectOption('1');await page.locator('#back2').click();
 await page.locator('#start').click();for(let i=0;i<6;i++){await page.locator('#carlist button').nth(i).click();await page.screenshot({path:info.outputPath(`car-${i}.png`)});}await page.locator('#tab1').click();await page.locator('#carlist button').nth(3).click();await expect(page.locator('#chosen')).toContainText('P2');await page.locator('#racebtn').click();await expect(page.locator('#countdown')).toHaveText('3');await page.evaluate(()=>MR.debug.skipCountdown());await page.keyboard.down('KeyW');await page.waitForTimeout(650);await page.keyboard.up('KeyW');
 const d=await page.evaluate(()=>MR.getDiagnostics());expect(d.vehicles[0].vz).toBeGreaterThan(1);expect(Math.abs(d.vehicles[1].vz)).toBeLessThan(.1);expect(Math.abs(d.cameras[0].z-d.cameras[1].z)).toBeGreaterThan(4);expect(d.drawCalls).toBeLessThan(110);expect(d.drawCalls).toBeGreaterThan(20);expect(errors).toEqual([]);
 await page.screenshot({path:info.outputPath('split-screen.png')});await page.locator('#quit').click();await expect(page.locator('#menu')).toBeVisible();await start(page);await expect(page.locator('#finish')).not.toBeVisible();
});
test('both keyboard players steer, brake/reverse, nitro and handbrake independently',async({page})=>{
 const errors=await load(page);await start(page);await page.keyboard.down('KeyW');await page.keyboard.down('ArrowUp');await page.keyboard.down('ShiftLeft');await page.keyboard.down('Enter');await page.waitForTimeout(650);await page.keyboard.down('KeyD');await page.keyboard.down('ArrowLeft');await page.keyboard.down('Space');await page.keyboard.down('ControlRight');await page.waitForTimeout(250);
 const d=await page.evaluate(()=>MR.getDiagnostics());expect(d.vehicles[0].n).toBeLessThan(100);expect(d.vehicles[1].n).toBeLessThan(100);expect(d.vehicles[0].steer).toBeLessThan(0);expect(d.vehicles[1].steer).toBeGreaterThan(0);expect(d.vehicles[0].wheelSpin).not.toBe(0);expect(d.vehicles[1].wheelSpin).not.toBe(0);
 for(const key of ['KeyW','ArrowUp','ShiftLeft','Enter','KeyD','ArrowLeft','Space','ControlRight'])await page.keyboard.up(key);
 const inputs=await page.evaluate(()=>MR.debug.input.sample());expect(inputs[0].throttle).toBe(0);expect(inputs[1].handbrake).toBe(0);
 await page.keyboard.down('KeyS');await page.keyboard.down('ArrowDown');await page.evaluate(()=>MR.debug.advance(4));await page.keyboard.up('KeyS');await page.keyboard.up('ArrowDown');const reversed=await page.evaluate(()=>MR.getDiagnostics());expect(reversed.vehicles[0].vz).toBeLessThan(0);expect(reversed.vehicles[1].vz).toBeLessThan(0);expect(errors).toEqual([]);
});
test('trusted four-finger touch, sliding outside a captured button and cancellation',async({page,context})=>{
 await load(page);await start(page);const cdp=await context.newCDPSession(page);const pts=await controlPoints(page,['[data-p="0"][data-k="g"]','[data-p="0"][data-k="r"]','[data-p="1"][data-k="g"]','[data-p="1"][data-k="l"]']);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:pts});await page.waitForTimeout(450);const before=await page.evaluate(()=>MR.getDiagnostics());expect(before.vehicles[0].vz).toBeGreaterThan(1);expect(before.vehicles[1].vz).toBeGreaterThan(1);expect(before.vehicles[0].steer).toBeLessThan(0);expect(before.vehicles[1].steer).toBeGreaterThan(0);
 pts[0].x-=160;await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:pts});const held=await page.evaluate(()=>MR.debug.input.sample());expect(held[0].throttle).toBe(1);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});const released=await page.evaluate(()=>MR.debug.input.sample());expect(released[0].throttle).toBe(0);expect(released[1].steer).toBe(0);
 const extra=await controlPoints(page,['[data-p="0"][data-k="n"]','[data-p="0"][data-k="d"]','[data-p="1"][data-k="b"]','[data-p="1"][data-k="d"]']);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:extra});const active=await page.evaluate(()=>MR.debug.input.sample());expect(active[0].nitro).toBe(1);expect(active[0].handbrake).toBe(1);expect(active[1].brake).toBe(1);expect(active[1].handbrake).toBe(1);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
});
test('real dynamics lap reaches results; stationary player cannot win; rematch resets',async({page})=>{
 await load(page);await page.locator('#set').click();await page.locator('#laps').selectOption('1');await page.locator('#back2').click();await start(page);
 const result=await page.evaluate(()=>{const track=MR.debug.track,target={},near={};for(let t=0;t<150;t+=1/120){const car=MR.debug.states[0];track.query(car.x,car.z,near);track.at(near.s+12+Math.abs(car.longitudinal)*.55,0,target);const error=Math.atan2(Math.sin(Math.atan2(target.x-car.x,target.z-car.z)-car.a),Math.cos(Math.atan2(target.x-car.x,target.z-car.z)-car.a)),speed=Math.hypot(car.vx,car.vz),desired=Math.max(9,25-Math.abs(error)*30);MR.debug.input.setGamepad(0,{steer:Math.max(-1,Math.min(1,-error*2.6)),throttle:speed<desired?1:0,brake:speed>desired+2?.45:0});MR.debug.advance(1/120);if(MR.getDiagnostics().winner>=0)break;}return MR.getDiagnostics();});
 expect(result.winner).toBe(0);expect(result.vehicles[0].lap).toBe(1);expect(result.vehicles[1].lap).toBe(0);await expect(page.locator('#finish')).toBeVisible();await expect(page.locator('#win')).toContainText('P1');await page.locator('#rematch').click();const fresh=await page.evaluate(()=>MR.getDiagnostics());expect(fresh.vehicles[0].lap).toBe(0);expect(fresh.winner).toBe(-1);expect(fresh.countdown).toBeGreaterThan(2);
});
for(const viewport of [{width:320,height:568},{width:393,height:852},{width:640,height:360},{width:1280,height:720}])test(`responsive UI and both viewports ${viewport.width}x${viewport.height}`,async({page},info)=>{
 await page.setViewportSize(viewport);const errors=await load(page);await start(page);const bounds=await page.evaluate(()=>{const selectors=['#quit',...Array.from(document.querySelectorAll('[data-p][data-k]'),b=>`[data-p="${b.dataset.p}"][data-k="${b.dataset.k}"]`)];return selectors.map(s=>{const r=document.querySelector(s).getBoundingClientRect();return {s,x:r.x,y:r.y,w:r.width,h:r.height};});});
 for(const b of bounds){expect(b.x).toBeGreaterThanOrEqual(0);expect(b.y).toBeGreaterThanOrEqual(0);expect(b.x+b.w).toBeLessThanOrEqual(viewport.width+1);expect(b.y+b.h).toBeLessThanOrEqual(viewport.height+1);}
 await page.keyboard.down('ArrowUp');await page.waitForTimeout(150);await page.keyboard.up('ArrowUp');expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('responsive.png')});
});

test('PC edition: side-by-side cameras, keyboard UI, layout settings, Escape pause and fullscreen',async({page},info)=>{
 await page.setViewportSize({width:1366,height:768});await page.goto('/?debug=1&platform=pc');await expect(page.locator('#start')).toBeEnabled();await expect(page.locator('body')).toHaveAttribute('data-layout','vertical');
 await expect(page.locator('.ctrl.c0')).not.toBeVisible();await page.locator('#start').click();await page.locator('#racebtn').click();await page.evaluate(()=>MR.debug.skipCountdown());await expect(page.locator('#keys0')).toBeVisible();await expect(page.locator('#keys1')).toBeVisible();
 const before=await page.evaluate(()=>{const track=MR.debug.track,out={};for(let p=0;p<2;p++){const car=MR.debug.states[p];track.at(50,p===0?-3:3,out);car.x=car.prevX=out.x;car.z=car.prevZ=out.z;car.a=0;car.vx=0;car.vz=12;}return MR.debug.states.map(c=>({x:c.x,z:c.z}));});
 await page.keyboard.down('KeyA');await page.keyboard.down('ArrowRight');await page.evaluate(()=>MR.debug.advance(.4));await page.keyboard.up('KeyA');await page.keyboard.up('ArrowRight');
 const d=await page.evaluate(()=>MR.getDiagnostics());expect(d.vehicles[0].x).toBeGreaterThan(before[0].x);expect(d.vehicles[1].x).toBeLessThan(before[1].x);expect(d.vehicles[0].steer).toBeGreaterThan(0);expect(d.vehicles[1].steer).toBeLessThan(0);
 await page.keyboard.press('Escape');await expect(page.locator('#pause')).toBeVisible();expect((await page.evaluate(()=>MR.getDiagnostics())).running).toBe(false);await page.keyboard.press('Escape');await expect(page.locator('#pause')).not.toBeVisible();
 await page.screenshot({path:info.outputPath('pc-split-screen.png')});await page.locator('#quit').click();await page.locator('#fullscreen').click();await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);await page.locator('#fullscreen').click();
 await page.locator('#set').click();await page.locator('#splitmode').selectOption('horizontal');await page.locator('#inputmode').selectOption('touch');await page.locator('#back2').click();await page.locator('#start').click();await page.locator('#racebtn').click();await expect(page.locator('body')).toHaveAttribute('data-layout','horizontal');await expect(page.locator('.ctrl.c0')).toBeVisible();
});

test('touch LEFT produces driver-left yaw for both players',async({page,context})=>{
 await load(page);await start(page);await page.evaluate(()=>{const out={};for(let p=0;p<2;p++){const car=MR.debug.states[p];MR.debug.track.at(50,p===0?-3:3,out);car.x=car.prevX=out.x;car.z=car.prevZ=out.z;car.a=0;car.vx=0;car.vz=12;}});
 const cdp=await context.newCDPSession(page),points=await controlPoints(page,['[data-p="0"][data-k="l"]','[data-p="1"][data-k="l"]']);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});await page.evaluate(()=>MR.debug.advance(.25));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const d=await page.evaluate(()=>MR.getDiagnostics());expect(d.vehicles.every(v=>v.steer>0&&v.a>0)).toBe(true);
});
