import test from 'node:test';import assert from 'node:assert/strict';
import {Track} from '../www/track.js';import {CAR_SPECS,buildCar} from '../www/cars.js';
import {createVehicle,stepVehicle,collideBarrier,collideCars,resetVehicle,FIXED_DT} from '../www/physics.js';
const track=new Track();const controls=()=>({steer:0,throttle:0,brake:0,nitro:0,handbrake:0});
function run(car,input,seconds,walls=false){for(let t=0;t<seconds;t+=FIXED_DT){stepVehicle(car,input,track);if(walls)collideBarrier(car,track);}}
function place(car,s,lateral=0){const out={};track.at(s,lateral,out);car.x=car.prevX=out.x;car.z=car.prevZ=out.z;car.a=Math.atan2(out.tx,out.tz);car.contact.index=out.index;}
test('circuit is closed, curved and has finite ordered gates',()=>{assert.ok(track.length>1200&&track.length<2500);assert.equal(track.gates.length,24);const q={},r={};track.at(0,0,q);track.at(track.length,0,r);assert.equal(q.x,r.x);assert.equal(q.z,r.z);assert.ok(new Set(track.samples.map(p=>Math.round(Math.atan2(p.tx,p.tz)*10))).size>20);});
test('six detailed meshes have distinct dimensions and roof silhouettes',()=>{const counts=[];for(const spec of CAR_SPECS){const m=buildCar(spec);assert.ok(m.body.vertexCount>1900);assert.ok(m.wheel.vertexCount>500);assert.ok(m.body.positions.every(Number.isFinite));assert.equal(m.body.positions.length,m.body.normals.length);counts.push(m.body.vertexCount);}assert.ok(new Set(counts).size>=4);assert.equal(new Set(CAR_SPECS.map(s=>`${s.height},${s.roofFront},${s.roofRear}`)).size,6);});
test('acceleration, drag, brakes, reverse and nitro are real forces',()=>{const car=createVehicle(CAR_SPECS[0],0,track),k=controls();k.throttle=1;run(car,k,3);const v=Math.hypot(car.vx,car.vz);assert.ok(v>12&&v<30);assert.notEqual(car.wheelSpin,0);k.nitro=1;run(car,k,1);assert.ok(car.n<100);k.nitro=0;k.throttle=0;k.brake=1;run(car,k,5);assert.ok(car.longitudinal< -1);assert.ok(car.n>70);k.brake=0;run(car,k,5);assert.ok(Math.abs(car.longitudinal)<8);});
test('inertia, speed-sensitive steering and controlled handbrake slip',()=>{const car=createVehicle(CAR_SPECS[0],0,track),k=controls();place(car,60);car.vz=24;k.throttle=.4;k.steer=.6;run(car,k,.6);const slip=Math.abs(car.lateral);assert.ok(Math.abs(car.yawRate)>.04);assert.ok(Math.abs(car.vx)>0);assert.ok(Math.hypot(car.vx,car.vz)>18);const angle=Math.abs(car.steerAngle);const slow=createVehicle(CAR_SPECS[0],0,track);run(slow,k,.6);assert.ok(Math.abs(slow.steerAngle)>angle);k.handbrake=1;run(car,k,.7);assert.ok(Math.abs(car.lateral)>slip+.1);assert.ok(Number.isFinite(car.a));});
test('grass and snow reduce traction and increase resistance',()=>{const a=createVehicle(CAR_SPECS[0],0,track),b=createVehicle(CAR_SPECS[0],0,track);place(a,40,0);place(b,40,11);const k=controls();k.throttle=1;run(a,k,1);run(b,k,1);assert.equal(b.surface,'grass');assert.ok(a.longitudinal>b.longitudinal+1);const snow={};track.query(140,-145,snow);assert.equal(snow.surface,'snow');});
test('barriers keep car inside and preserve tangential velocity',()=>{const car=createVehicle(CAR_SPECS[0],0,track);place(car,60,13.2);car.vx=9;car.vz=20;assert.ok(collideBarrier(car,track));track.query(car.x,car.z,car.contact);assert.ok(Math.abs(car.contact.lateral)<13);assert.ok(car.vx<0);assert.ok(car.vz>16);const k=controls();k.throttle=1;k.steer=1;run(car,k,12,true);assert.ok(Number.isFinite(car.x));assert.ok(Math.abs(car.contact.lateral)<=track.barrierOffset);});
test('car collision transfers momentum and resolves overlap',()=>{const a=createVehicle(CAR_SPECS[0],0,track),b=createVehicle(CAR_SPECS[0],1,track);a.x=0;a.z=0;a.a=0;b.x=0;b.z=3.9;b.a=0;a.vz=20;b.vz=0;assert.ok(collideCars(a,b));assert.ok(b.vz>8);assert.ok(a.vz<15&&a.vz>0);assert.ok(b.z-a.z>=a.spec.length);assert.equal(collideCars(a,b),false);});
test('stationary, backwards, skipped gates and finish shortcuts cannot award a lap',()=>{const car=createVehicle(CAR_SPECS[0],0,track);for(let i=0;i<1000;i++)track.updateProgress(car,FIXED_DT);assert.equal(car.progress.completed,0);const gate=track.gates[0];car.prevX=gate.x-gate.tx;car.prevZ=gate.z-gate.tz;car.x=gate.x+gate.tx;car.z=gate.z+gate.tz;track.updateProgress(car,FIXED_DT);assert.equal(car.progress.completed,0);assert.equal(car.progress.next,1);const next=track.gates[1];car.prevX=next.x+next.tx;car.prevZ=next.z+next.tz;car.x=next.x-next.tx;car.z=next.z-next.tz;track.updateProgress(car,FIXED_DT);assert.equal(car.progress.next,1);});
test('forward crossings of all gates award exactly one lap, reset preserves progress',()=>{const car=createVehicle(CAR_SPECS[0],0,track);for(let i=1;i<=24;i++){const gate=track.gates[i%24];car.prevX=gate.x-gate.tx*.5;car.prevZ=gate.z-gate.tz*.5;car.x=gate.x+gate.tx*.5;car.z=gate.z+gate.tz*.5;track.updateProgress(car,FIXED_DT);}assert.equal(car.progress.completed,1);assert.equal(car.progress.next,1);assert.ok(resetVehicle(car,track));assert.equal(car.progress.completed,1);assert.equal(car.progress.next,1);assert.equal(resetVehicle(car,track),false);});
// Real tire physics + look-ahead driver: a full lap must be navigable for every class.
export function driveLap(spec){const car=createVehicle(spec,0,track),k=controls(),target={},near={};let maxOffset=0;
 for(let t=0;t<180;t+=FIXED_DT){track.query(car.x,car.z,near);track.at(near.s+12+Math.abs(car.longitudinal)*.55,0,target);const angle=Math.atan2(target.x-car.x,target.z-car.z),error=Math.atan2(Math.sin(angle-car.a),Math.cos(angle-car.a));const speed=Math.hypot(car.vx,car.vz);
  k.steer=Math.max(-1,Math.min(1,error*2.6));const desired=Math.max(9,25-Math.abs(error)*30);k.throttle=speed<desired?1:0;k.brake=speed>desired+2?.45:0;
  stepVehicle(car,k,track);collideBarrier(car,track);track.updateProgress(car,FIXED_DT);maxOffset=Math.max(maxOffset,Math.abs(car.contact.lateral));if(car.progress.completed===1)return {time:t,maxOffset,collisions:car.collisionCount};
 }return {time:Infinity,maxOffset,collisions:car.collisionCount,next:car.progress.next};}
test('every car can complete an actual lap under the real dynamics',()=>{for(const spec of CAR_SPECS){const result=driveLap(spec);console.log(spec.class,result);assert.ok(result.time<180,`${spec.name}: checkpoint ${result.next}`);assert.ok(result.maxOffset<10,`${spec.name}: excessive corner drift`);assert.equal(result.collisions,0);}});
